In [1]:
import tensorflow as tf

상수를 이용한 add

In [2]:
a = tf.constant(3.0, tf.float32)

In [3]:
b = tf.constant(4.0, tf.float32)  # tf.float32 : dtype

In [4]:
x = tf.add(a, b)

 1차원 배열을 이용한 add

In [9]:
import tensorflow as tf

In [10]:
a = tf.constant([5], dtype=tf.float32)

In [11]:
b = tf.constant([10], dtype=tf.float32)

In [12]:
c = tf.constant([4], dtype=tf.float32)

In [13]:
d = a * b + c #배열을 일반 숫자처럼 연산?

In [14]:
print(d)       

Tensor("add_1:0", shape=(1,), dtype=float32)


In [15]:
sess = tf.Session()

In [16]:
print(sess.run(d))

[54.]


In [17]:
print(d.shape)              #요소가 1개짜리

(1,)


In [18]:
print(sess.run(tf.rank(d)))

1


2차원 데이터의 연산

In [20]:
import tensorflow as tf

In [21]:
a = tf.constant([2, 3])     #파이썬 리스트사용 #1차원 요소 2개

In [22]:
b = tf.constant([[0, 1], [2, 3]])      #2차원 요소 2개

In [23]:
x = tf.add(a, b)         #연산 시 차원이 다르면 차원을 맞춤

In [24]:
y = tf.multiply(a, b)

In [26]:
sess = tf.Session()

In [68]:
print(sess.run(z))

[[14]]


In [28]:
print(sess.run(y))

[[0 3]
 [4 9]]


y의 rank, shape 확인

In [31]:
sess.run(tf.rank(y))

2

In [32]:
print(y.shape)         #(a,b) b가 각 요소의 개수

(2, 2)


matrix multiply

In [34]:
a = tf.constant([[2, 2]]) # 2차원

In [35]:
b = tf.constant([[0, 1], [2, 3]]) # 2차원

In [36]:
z = tf.matmul(a, b) #matrix 곱

In [37]:
sess.run(z) # 결과값?

array([[4, 8]])

In [39]:
print(z.shape)

(1, 2)


In [41]:
sess.run(tf.rank(z))

2

In [ ]:
Vector, matrix 곱

In [42]:
A = tf.constant(2)

In [43]:
B = tf.constant([[1,6],[3, 4], [6, 2]])

In [44]:
C = tf.multiply(A, B)

In [50]:
print(sess.run(C))

[[ 2 12]
 [ 6  8]
 [12  4]]


In [47]:
D = tf.constant([[3],[2],[1]])

In [48]:
F = tf.multiply(A,D)

In [51]:
print(sess.run(F))

[[6]
 [4]
 [2]]


Matrix곱

In [52]:
a = tf.constant([[1,6],[3,4],[5,2]])

In [53]:
b = tf.constant([[1,-1],[2, 1]])

In [60]:
c = tf.matmul(a, b)

ValueError: Shape must be rank 2 but is rank 1 for 'MatMul_3' (op: 'MatMul') with input shapes: [3], [3,1].

In [66]:
sess.run(c)

array([[14]])

In [89]:
a = tf.constant([[3,2,1]])

In [90]:
b = tf.constant([[1],[3],[5]])

In [91]:
c = tf.matmul(a,b)

In [75]:
print(sess.run(c))

[[14]]


In [97]:
a = tf.constant([[1],[3],[5]])

In [98]:
b = tf.constant([[1,2]])

In [102]:
x = tf.matmul(a,b)

In [103]:
print(sess.run(x))

[[ 1  2]
 [ 3  6]
 [ 5 10]]
