In [1]:
nestedMathList = [[11,12,13], [21,22,23], [31,32,33]]

In [2]:
print(nestedMathList)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]


In [3]:
nestedMathList2 = []

for list in nestedMathList:
    tempList = []
    
    for e in list:
        tempList.append(e+1)
    nestedMathList2.append(tempList)

print(nestedMathList2)

[[12, 13, 14], [22, 23, 24], [32, 33, 34]]


In [4]:
import numpy as np

In [5]:
mathNdarray = np.array(nestedMathList)
# mathNdarray = np.array([[11,12,13],[21,22,23],[24,25,26]])

print(mathNdarray)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [7]:
mathNdarray + 1 #이것이 바로 브로드캐스팅!(numpy array여야 가능)

# Numpy에 구현된 메서드를 활용해 합이나 평균도 쉽게 구할 수 있음

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [8]:
# 전체 합 구하기
np.sum(mathNdarray)

198

In [10]:
# 전체 평균 구하기(mean(): 산술평균, average(): 가중치 평균)
np.mean(mathNdarray)

22.0

In [12]:
# 열의 평균 구하기 
np.mean(mathNdarray, axis = 0)

array([21., 22., 23.])

In [11]:
# 행 평균 구하기
np.mean(mathNdarray, axis = 1)

array([12., 22., 32.])

In [13]:
rows = 1000 #행
cols = 1000 #열
sampleRand2Darray = np.random.rand(rows, cols)  #ndarray 
sampleRand2Dlist = sampleRand2Darray.tolist() # nested

In [ ]:
#rows, cols가 1000을 넘어갈때는 실행하지 말 것 (노트북 멈춤)
sampleRand2Darray

In [14]:
x = np.array([[1,2],[3,4]], dtype=np.int8)  #8bit byte
y = x.T  #전치행렬

In [15]:
x

array([[1, 2],
       [3, 4]], dtype=int8)

In [16]:
y

array([[1, 3],
       [2, 4]], dtype=int8)

In [1]:
import numpy as np

In [4]:
#3차원
myary = np.array(
[
    [
        [1,  2,   3], #[ 0,0,0      0,0,1     0,0,2]
        [11, 12, 13], #[ 0,1,0      0,1,1     0,1,2]
        [21, 22, 23], #[ 0,2,0      0,2,1     0,2,2]
        [31, 32, 33]  #[ 0,3,0      0,3,1     0,3,2]
    ],
    
    [
        [1,  2,   3], #[ 1,0,0      1,0,1     1,0,2]
        [11, 12, 13], #[ 1,1,0      1,1,1     1,1,2]
        [21, 22, 23], #[ 1,2,0      1,2,1     1,2,2]
        [31, 32, 33]  #[ 1,3,0      1,3,1     1,3,2]
    ]
]
)

In [5]:
print("myarray 차원 : {}, shape : {} ".format(myary.ndim,myary.shape))

myarray 차원 : 3, shape : (2, 4, 3) 


In [7]:
myary

array([[[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]],

       [[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]]])

In [8]:
np.sum(myary) #모든 요소의 합

408

In [9]:
np.sum(myary, axis=0) # axis = 0 요소의 합 ==> 출력 결과

array([[ 2,  4,  6],
       [22, 24, 26],
       [42, 44, 46],
       [62, 64, 66]])

In [10]:
np.sum(myary, axis=1) # axis = 1 요소의 합 ==> 출력 결과

array([[64, 68, 72],
       [64, 68, 72]])

In [11]:
np.sum(myary, axis=2) # axis = 2 요소의 합 ==> 출력 결과

array([[ 6, 36, 66, 96],
       [ 6, 36, 66, 96]])

데이터 타입

In [ ]:
#booleen

In [13]:
boolArray = np.array([True, False, True, True, False])

In [14]:
boolArray

array([ True, False,  True,  True, False])

In [15]:
boolArray.dtype

dtype('bool')

In [ ]:
#정수형

In [16]:
intArray = np.array([[1, 2],[3, 4]])

In [17]:
intArray

array([[1, 2],
       [3, 4]])

In [18]:
intArray.dtype

dtype('int32')

In [19]:
floatArray = np.array([[1.1, 2.2], [3.3, 4.4]])

floatArray

In [21]:
floatArray.dtype

dtype('float64')

형변환

In [26]:
floatArray2 = np.array([[1,2], [3,4]], dtype='float64')

In [28]:
floatArray2.dtype

dtype('float64')

표준 코딩 방법

In [23]:
floatArray3 = np.array([[1., 2.],[3., 4.]])

In [24]:
floatArray3

array([[1., 2.],
       [3., 4.]])

In [25]:
floatArray3.dtype

dtype('float64')

다차원 배열 생성 -2

numpy.empty

엔트리를 초기화하지 않고(비우는게 아님) 지정된 형태 및 새로운 배열을 생성

In [29]:
np.empty((4,3))    #쓰레기 값이 만들어진 배열 생성

array([[4.24399158e-314, 2.33419537e-313, 2.75859453e-313],
       [4.66839074e-313, 6.57818695e-313, 7.00258611e-313],
       [4.24399158e-314, 2.33419537e-313, 2.75859453e-313],
       [4.66839074e-313, 6.57818695e-313, 7.00258611e-313]])

In [30]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [31]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.empty_like(A) #주어진 모양과 같은 유형의 새로운 배열을 만들어라

array([[1259179288,        438,          0],
       [         0,          0,          0],
       [-689431182, -669649596,          0]])

In [33]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
np.zeros_like(A) #지정된 배열과 같은 새로운 배열 생성

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones((2, 3)).dtype

dtype('float64')

In [37]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones_like(A)

In [43]:
np.identity(2)     #대각선에 있는 데이터만 1로 만듦(단위행렬(정방행렬)로)

array([[1., 0.],
       [0., 1.]])

In [44]:
np.identity(3, dtype=int) #대각선에 1을, 그 외에 0을 가지는 2차원 배열

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
import tensorflow as tf

In [67]:
a = tf.identity(3)
sess = tf.Session()
sess.run(a)

3

In [45]:
np.eye(3)      

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
#tensorflow
a = tf.eye(3)
sess.run(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [46]:
np.eye(3, 4)   #identity와 다르게 정방행렬이 아닌 스퀘어도 만들 수 있음

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [47]:
np.eye(3, 4, 1)   #세번째 값은 1이 들어가는 위치를 오른쪽으로 한 칸 이동함

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.eye(3, 4, -1)  #세번째 값은 1이 들어가는 위치를 아래로 한 칸 이동함

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [49]:
np.full((2, 3), 10)  #2행 3열 짜리를 만들어서 10으로 채움

array([[10, 10, 10],
       [10, 10, 10]])

In [50]:
10 * np.ones((2, 3), dtype=int)  #이 방법을 더 선호

array([[10, 10, 10],
       [10, 10, 10]])

numpy.arange
지정된 간격 내에서 균등하게 간격을 둔 값

In [51]:
#default vlaue
#start = 0
#step = 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(start=1.0, stop=5.0, step=0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [54]:
import tensorflow as tf

In [55]:
start = 3
limit = 18
delta = 3
a = tf.range(start, limit, delta) #[3, 6, 9, 12, 15]

sess = tf.Session()
sess.run(a)

array([ 3,  6,  9, 12, 15])

numpy.amin
axis을 따른 배열 또는 최소의 최소치

In [73]:
A = np.array([[1, 2, 33], [14, 5, 6], [97, 8, 9]])

In [74]:
A

array([[ 1,  2, 33],
       [14,  5,  6],
       [97,  8,  9]])

In [75]:
np.amin(A, axis = 0)

array([1, 2, 6])

In [76]:
np.amin(A, 1)   #부적절

array([1, 5, 8])

In [78]:
np.amin(A)

1

In [91]:
import tensorflow as tf
x = tf.constant([[1, 2, 1], [1, 5,  1], [7, 8, 9]])
y = tf.constant([[1, 5, 3], [4, 5, 20], [1, 8, 9]])

a = tf.constant([1,6,2])
b = tf.constant([9,1,5])
sess = tf.Session()
sess.run(tf.minimum(a, b))
sess.run(tf.minimum(x, y))

array([[1, 2, 1],
       [1, 5, 1],
       [1, 8, 9]])

In [87]:
sess.close()

In [94]:
np.amax(A, 0) # np.amax(A, axis=0)

array([97,  8, 33])

In [95]:
np.amax(A, 1) # np,amax(A, axis=1)

array([33, 14, 97])

In [96]:
np.amax(A, 1).shape

(3,)

In [93]:
np.amax(A)

97

In [92]:
np.median(A, 0)  #중간 값

array([14.,  5.,  9.])

In [97]:
np.median(A, 1)

array([2., 6., 9.])

In [98]:
np.median(A)

8.0

numpy.mean
- 축을 따라 산술 평균을 계산
- 가중평균을 구하려면 numpy.average를 사용 

In [99]:
A

array([[ 1,  2, 33],
       [14,  5,  6],
       [97,  8,  9]])

In [100]:
np.mean(A, 0)

array([37.33333333,  5.        , 16.        ])

In [101]:
np.mean(A, 1)

array([12.        ,  8.33333333, 38.        ])

In [ ]:
#다차원 배열 다루기2
1. 슬라이싱
파이썬 리스트와 유사하게, Numpy배열도 슬라이싱이 가능
- Numpy 배열은 다차원인 경우가 많기 떄문에 각 차원별로 어떻게 슬라이스 할 건지 명확히 해야한다.
- Numpy 배열은 슬라이싱하면, 연속된 값을 가져오기에 결과로 얻어지는 배열은 언제나 원본 배열의 부분 배열


In [3]:
#shape가 (3, 4)인 2차원 배열 생성
#[ [ 1 2 3 4 ]
#  [5 6 7 8 ]
#  [9 10 11 12]]
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

슬라이싱 하는 방법
- a[행 슬라이싱 시작:행 슬라이싱 끝, 열 슬라이싱 시작:열 슬라이싱 끝]
- 시작 값부터 끝 값 전까지 슬라이싱

In [103]:
a[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
a[:2, :] # 위와 동일

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
a[:2]
#열을 슬라이싱 하지 않는 코드이며 이런 경우 열 부분은 전체 생략 가능
#(행을 슬라이싱 하지 않는다고 하더라도 행부분을 생략할 순 없다.)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

2. 인덱싱
두가지 방법이 있다.

In [109]:
# 선호하는 방식
a[0, 0]    #a[0][0]보다 선호

1

- numpy배열을 슬라이싱하면 연속된 값을 가져오기에 결과로 얻어지는 배열은 언제나 원본 배열의 부분 배열
- 그러나 인덱싱하면 연속하지 않은 값도 가져올 수 있으므로 원본과 다른 배열을 만들 수 있다.

In [110]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
# 콜론으로 데이터를 가져오지 않으면 인덱싱이다
# 0행, 2행만 인덱싱
a[[0,2],]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
# 0열, 1열, 3열만 인덱싱

In [112]:
a[:, [0,1,3]]   #앞부분은 슬라이싱, 뒷부분은 인덱싱

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

인덱싱 & 슬라이싱 ` 차원
- 정수 인덱싱과 슬라이싱을 혼합해서 사용하면 낮은 차원의 배열이 생성 되지만, 슬라이싱만 사용하면 
원본 배열과 동일한 차원의 배열 생성
- 0번째 행을 인덱싱하는 경우와 슬라이싱 하는 경우의 예

In [113]:
print(a, a.shape, a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2


In [115]:
#슬라이싱만 사용
slicedRow = a[0:1, :]
print(slicedRow, slicedRow.shape, slicedRow.ndim)

[[1 2 3 4]] (1, 4) 2


In [117]:
#인덱싱 & 슬라이싱 혼합 사용 => 차원이 하나 감소
indexedRow = a[0, :]
print(indexedRow, indexedRow.shape, indexedRow.ndim)

[1 2 3 4] (4,) 1


열의 경우

In [118]:
#슬라이싱만 사용
slicedCol = a[:, 0:1]
print(slicedCol, slicedCol.shape, slicedCol.ndim)

[[1]
 [5]
 [9]] (3, 1) 2


In [120]:
#인덱싱 & 슬라이싱 혼합 사용
indexedCol = a[:, 0]
print(indexedCol, indexedCol.shape, indexedCol.ndim)

[1 5 9] (3,) 1


인덱싱 & 슬라이싱 값 복사&참조
- 인덱싱은 값을 복사하므로 복사된 값을 변경해도 원본의 값은 변하지 않는다.
특별히 인덱싱을 써야하는 상황이 아니라면 인덱싱보다 슬라이싱 추천

In [4]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
# 인덱싱해서 b에 대입
b = a[0, 0]

In [6]:
b

1

In [8]:
b = 100

In [9]:
print("a[0, 0]:{}".format(a[0,0]))
print("b: {}".format(b))

a[0, 0]:1
b: 100


슬라이싱된 배열은 원본 배열과 같은 데이터를 참조한다.
즉 슬라이시된 배열을 수정하면 원본 배열 역시 수정됨

In [10]:
# a를 슬라이스 하여 c 생성
c = a[1:3, 1:3]
print(c)

[[ 6  7]
 [10 11]]


In [12]:
# c[0,0]은 a[1,1]과 같은 데이터
c[0, 0]= 100

In [13]:
print(c)
print('---------------')
print(a)

[[100   7]
 [ 10  11]]
---------------
[[  1   2   3   4]
 [  5 100   7   8]
 [  9  10  11  12]]


In [ ]:
shape변경
numpy.reshape
- 데이터를 변경하지 않고 새로운  shape으로 수정

In [14]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [15]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
a = np.arange(6).reshape(2,3)

In [18]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
numpy.ndarray.flatten()
- 접힌 배열의 복사본을 하나의 차원으로 전환

In [20]:
#np.flatten(a) # Numpy 모듈 함수가 아님
a.flatten() # ndarray 객체이 메소드로만 사용 가능

array([0, 1, 2, 3, 4, 5])

In [19]:
a

array([[0, 1, 2],
       [3, 4, 5]])

numpy.concatenate

In [26]:
a = np.array([[1, 2],[3, 4]])

In [25]:
b = np.array([[5, 6]])

In [27]:
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a[0:1].T

In [28]:
b.T

array([[5, 7],
       [6, 8]])

In [ ]:
행의 개수가 같아야 axis = 1, 즉 옆으로 연결 가능

In [ ]:
np.concatenate((a, b.T), axis = 1)

백터의 내적, 벅터와 행렬의 곱, 행렬 곱
- Numpy에서는 + 대신 dot함수 사용

In [30]:
import numpy as np

In [31]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [32]:
v = np.array([9, 10])
w = np.array([11, 12])

In [33]:
# 백터의 내적; 결과 동일
print(v.dot(w))
print(np.dot(v, w))

219
219


In [34]:
# 행렬과 백터의 곱; dimension 1인 배열
# s : 값, vector : 1차원배열, matrix: 2차원 배열, tensor: 3,4,,,n차원
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [35]:
import tensorflow as tf

In [36]:
a = tf.constant([[1, 2],[3, 4]])
b = tf.constant([[5, 6],[7,8]])
c = tf.constant([9, 10])
d = tf.constant([11, 12])

In [40]:
#a와 c를 matmul할 때, c의 차원바꾸기
#constant는 reshape불가(이미 그래프에 들어가서)
result = tf.matmul(a, tf.reshape(c,(2,1)))

In [42]:
sess = tf.Session()

In [43]:
sess.run(result)

array([[29],
       [67]])

Numpy의 고급 기능
- 브로드캐스팅은 Numpy에서 shape가 다른 배열 간에도 산술 연산이 가능하게 해준다
- 작은 배열과 큰 배열이 있을 때, 큰 배열을 대상으로 작은 배열을 여러 번 연산하고자 할 때

In [44]:
import numpy as np

In [45]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [47]:
v = np.array([1,0,1])

In [48]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
x.shape

(4, 3)

In [52]:
y = np.empty_like(x) # x와 동일한 shape를 가지며 비어있는 행렬 생성

In [53]:
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#

In [ ]:
x = np.array([1,2,3],[4,5,6],[7,8,9],[10,11,12])
v = np.array([1,0,1])

In [ ]:
y = x + v # 브로드캐스팅을 이용하여 v를 x의 각 행에 더하기

In [ ]:
y 