# Session 사용방법
 1) Session 객체를 이용하는 방법 -> close()해야함

In [2]:
import tensorflow as tf

In [3]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [4]:
z = tf.matmul(x, y)

In [6]:
sess = tf.Session()

In [8]:
print(sess.run(z, feed_dict={x:[[3., 3.], [3.,3.]], y:[[5., 5.], [5., 5.]]} ))

[[30. 30.]
 [30. 30.]]


In [10]:
sess.close()

2) with를 이용한 session객체의 사용
with 블록안에서 session 이용하면 자동으로 session 이 close됨

In [13]:
import tensorflow as tf

In [14]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [16]:
z = tf.matmul(x, y)

In [17]:
with tf.Session() as sess : 
    print(sess.run(z, feed_dict={x:[[3., 3.], [3.,3.]], y:[[5., 5.], [5., 5.]]} ))

[[30. 30.]
 [30. 30.]]


3) InteractiveSession()
- run()을 하지 않고 eval()을 사용해서 출력결과를 바로 확인 가능

In [19]:
import tensorflow as tf

In [20]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [24]:
z = tf.matmul(x, y)

In [25]:
sess = tf.InteractiveSession()

In [27]:
print(z.eval(feed_dict={x:[[3., 3.], [3.,3.]], y:[[5., 5.], [5., 5.]]} ))

[[30. 30.]
 [30. 30.]]


In [23]:
sess.close()